terms:
  - id:
    term:
  - id: Account books
    term: Account books
  - id: Advertisements
    term: Advertisements
  - id: Albumen prints
    term: Albumen prints
  - id: Architectural drawings
    term: Architectural drawings
  - id: Bird's-eye view prints
    term: Bird's-eye view prints
  - id: Birthday cards
    term: Birthday cards
  - id: Book covers
    term: Book covers
  - id: Book illustrations
    term: Book illustrations
  - id: Books
    term: Books
  - id: Boudoir card photographs
    term: Boudoir card photographs
  - id: Cabinet photographs
    term: Cabinet photographs
  - id: Carbon prints
    term: Carbon prints
  - id: Cartes de visite
    term: Cartes de visite
  - id: Cased photographs
    term: Cased photographs
  - id: Catalogs
    term: Catalogs
  - id: Charcoal drawings
    term: Charcoal drawings
  - id: Cigarette cards
    term: Cigarette cards
  - id: Collages
    term: Collages
  - id: Contact prints
    term: Contact prints
  - id: Contact sheets
    term: Contact sheets
  - id: Digital images
    term: Digital images
  - id: Documents
    term: Documents
  - id: Drawings
    term: Drawings
  - id: Dye coupler negatives
    term: Dye coupler negatives
  - id: Engravings
    term: Engravings
  - id: Etchings
    term: Etchings
  - id: Exhibition catalogs
    term: Exhibition catalogs
  - id: Film negatives
    term: Film negatives
  - id: Forms (Documents)
    term: Forms (Documents)
  - id: Gelatin silver printing-out paper prints
    term: Gelatin silver printing-out paper prints
  - id: Gelatin silver prints
    term: Gelatin silver prints
  - id: Glass negatives
    term: Glass negatives
  - id: Halftone photomechanical prints
    term: Halftone photomechanical prints
  - id: Illuminated manuscripts
    term: Illuminated manuscripts
  - id: Illuminations
    term: Illuminations
  - id: Illustrations
    term: Illustrations
  - id: Imperial card photographs
    term: Imperial card photographs
  - id: Indexes
    term: Indexes
  - id: Ink drawings
    term: Ink drawings
  - id: Intaglio prints
    term: Intaglio prints
  - id: Landscape drawings
    term: Landscape drawings
  - id: Lithographs
    term: Lithographs
  - id: Manuscripts
    term: Manuscripts
  - id: Maps
    term: Maps
  - id: Metal cuts
    term: Metal cuts
  - id: Montages
    term: Montages
  - id: Negatives
    term: Negatives
  - id: Newspapers
    term: Newspapers
  - id: Nitrate negatives
    term: Nitrate negatives
  - id: Oil paintings
    term: Oil paintings
  - id: Paintings
    term: Paintings
  - id: Panel card photographs
    term: Panel card photographs
  - id: Pencil works
    term: Pencil works
  - id: Periodicals
    term: Periodicals
  - id: Photographic postcards
    term: Photographic postcards
  - id: Photographic prints
    term: Photographic prints
  - id: Photogravures
    term: Photogravures
  - id: Photomechanical prints
    term: Photomechanical prints
  - id: Planographic prints
    term: Planographic prints
  - id: Platinum prints
    term: Platinum prints
  - id: Plats
    term: Plats
  - id: Playbills
    term: Playbills
  - id: Portrait paintings
    term: Portrait paintings
  - id: Postcards
    term: Postcards
  - id: Posters
    term: Posters
  - id: Prints
    term: Prints
  - id: Programs
    term: Programs
  - id: Promenade card photographs
    term: Promenade card photographs
  - id: Registers
    term: Registers
  - id: Relief prints
    term: Relief prints
  - id: Reproductions
    term: Reproductions
  - id: Safety film negatives
    term: Safety film negatives
  - id: School yearbooks
    term: School yearbooks
  - id: Screen prints
    term: Screen prints
  - id: Silver printing-out paper prints
    term: Silver printing-out paper prints
  - id: Site plans
    term: Site plans
  - id: Slides
    term: Slides
  - id: Sound recordings
    term: Sound recordings
  - id: Stereographs
    term: Stereographs
  - id: Tintypes
    term: Tintypes
  - id: Title pages
    term: Title pages
  - id: Trade cards
    term: Trade cards
  - id: Transcripts
    term: Transcripts
  - id: Video recording
    term: Video recording
  - id: Wash drawings
    term: Wash drawings
  - id: Watercolors
    term: Watercolors
  - id: Wood engravings
    term: Wood engravings
  - id: Woodcuts
    term: Woodcuts
